# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import shared_pb2 as shared__pb2


class AgentStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoBackup = channel.stream_stream(
        '/lbackgrpc.Agent/DoBackup',
        request_serializer=shared__pb2.BackupCmd.SerializeToString,
        response_deserializer=shared__pb2.BackupCmdStatus.FromString,
        )
    self.DoMv = channel.unary_unary(
        '/lbackgrpc.Agent/DoMv',
        request_serializer=shared__pb2.MvCmd.SerializeToString,
        response_deserializer=shared__pb2.MvCmdStatus.FromString,
        )
    self.DoRestore = channel.unary_stream(
        '/lbackgrpc.Agent/DoRestore',
        request_serializer=shared__pb2.RestoreCmd.SerializeToString,
        response_deserializer=shared__pb2.RestoreCmdStatus.FromString,
        )
    self.DoRm = channel.unary_unary(
        '/lbackgrpc.Agent/DoRm',
        request_serializer=shared__pb2.RmCmd.SerializeToString,
        response_deserializer=shared__pb2.RmCmdStatus.FromString,
        )


class AgentServicer(object):
  """Interface exported by the server.
  """

  def DoBackup(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoMv(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoRestore(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoRm(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoBackup': grpc.stream_stream_rpc_method_handler(
          servicer.DoBackup,
          request_deserializer=shared__pb2.BackupCmd.FromString,
          response_serializer=shared__pb2.BackupCmdStatus.SerializeToString,
      ),
      'DoMv': grpc.unary_unary_rpc_method_handler(
          servicer.DoMv,
          request_deserializer=shared__pb2.MvCmd.FromString,
          response_serializer=shared__pb2.MvCmdStatus.SerializeToString,
      ),
      'DoRestore': grpc.unary_stream_rpc_method_handler(
          servicer.DoRestore,
          request_deserializer=shared__pb2.RestoreCmd.FromString,
          response_serializer=shared__pb2.RestoreCmdStatus.SerializeToString,
      ),
      'DoRm': grpc.unary_unary_rpc_method_handler(
          servicer.DoRm,
          request_deserializer=shared__pb2.RmCmd.FromString,
          response_serializer=shared__pb2.RmCmdStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'lbackgrpc.Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
