# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='lbackgrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\tlbackgrpc\x1a\x0cshared.proto2\xf8\x01\n\x05\x41gent\x12\x42\n\x08\x44oBackup\x12\x14.lbackgrpc.BackupCmd\x1a\x1a.lbackgrpc.BackupCmdStatus\"\x00(\x01\x30\x01\x12\x32\n\x04\x44oMv\x12\x10.lbackgrpc.MvCmd\x1a\x16.lbackgrpc.MvCmdStatus\"\x00\x12\x43\n\tDoRestore\x12\x15.lbackgrpc.RestoreCmd\x1a\x1b.lbackgrpc.RestoreCmdStatus\"\x00\x30\x01\x12\x32\n\x04\x44oRm\x12\x10.lbackgrpc.RmCmd\x1a\x16.lbackgrpc.RmCmdStatus\"\x00\x42\x1d\n\x12io.grpc.lback.grpcB\x05\x41gentP\x01\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022io.grpc.lback.grpcB\005AgentP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class AgentStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.DoBackup = channel.stream_stream(
          '/lbackgrpc.Agent/DoBackup',
          request_serializer=shared__pb2.BackupCmd.SerializeToString,
          response_deserializer=shared__pb2.BackupCmdStatus.FromString,
          )
      self.DoMv = channel.unary_unary(
          '/lbackgrpc.Agent/DoMv',
          request_serializer=shared__pb2.MvCmd.SerializeToString,
          response_deserializer=shared__pb2.MvCmdStatus.FromString,
          )
      self.DoRestore = channel.unary_stream(
          '/lbackgrpc.Agent/DoRestore',
          request_serializer=shared__pb2.RestoreCmd.SerializeToString,
          response_deserializer=shared__pb2.RestoreCmdStatus.FromString,
          )
      self.DoRm = channel.unary_unary(
          '/lbackgrpc.Agent/DoRm',
          request_serializer=shared__pb2.RmCmd.SerializeToString,
          response_deserializer=shared__pb2.RmCmdStatus.FromString,
          )


  class AgentServicer(object):
    """Interface exported by the server.
    """

    def DoBackup(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def DoMv(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def DoRestore(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def DoRm(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'DoBackup': grpc.stream_stream_rpc_method_handler(
            servicer.DoBackup,
            request_deserializer=shared__pb2.BackupCmd.FromString,
            response_serializer=shared__pb2.BackupCmdStatus.SerializeToString,
        ),
        'DoMv': grpc.unary_unary_rpc_method_handler(
            servicer.DoMv,
            request_deserializer=shared__pb2.MvCmd.FromString,
            response_serializer=shared__pb2.MvCmdStatus.SerializeToString,
        ),
        'DoRestore': grpc.unary_stream_rpc_method_handler(
            servicer.DoRestore,
            request_deserializer=shared__pb2.RestoreCmd.FromString,
            response_serializer=shared__pb2.RestoreCmdStatus.SerializeToString,
        ),
        'DoRm': grpc.unary_unary_rpc_method_handler(
            servicer.DoRm,
            request_deserializer=shared__pb2.RmCmd.FromString,
            response_serializer=shared__pb2.RmCmdStatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'lbackgrpc.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAgentServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Interface exported by the server.
    """
    def DoBackup(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def DoMv(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def DoRestore(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def DoRm(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAgentStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Interface exported by the server.
    """
    def DoBackup(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    def DoMv(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    DoMv.future = None
    def DoRestore(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    def DoRm(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    DoRm.future = None


  def beta_create_Agent_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('lbackgrpc.Agent', 'DoBackup'): shared__pb2.BackupCmd.FromString,
      ('lbackgrpc.Agent', 'DoMv'): shared__pb2.MvCmd.FromString,
      ('lbackgrpc.Agent', 'DoRestore'): shared__pb2.RestoreCmd.FromString,
      ('lbackgrpc.Agent', 'DoRm'): shared__pb2.RmCmd.FromString,
    }
    response_serializers = {
      ('lbackgrpc.Agent', 'DoBackup'): shared__pb2.BackupCmdStatus.SerializeToString,
      ('lbackgrpc.Agent', 'DoMv'): shared__pb2.MvCmdStatus.SerializeToString,
      ('lbackgrpc.Agent', 'DoRestore'): shared__pb2.RestoreCmdStatus.SerializeToString,
      ('lbackgrpc.Agent', 'DoRm'): shared__pb2.RmCmdStatus.SerializeToString,
    }
    method_implementations = {
      ('lbackgrpc.Agent', 'DoBackup'): face_utilities.stream_stream_inline(servicer.DoBackup),
      ('lbackgrpc.Agent', 'DoMv'): face_utilities.unary_unary_inline(servicer.DoMv),
      ('lbackgrpc.Agent', 'DoRestore'): face_utilities.unary_stream_inline(servicer.DoRestore),
      ('lbackgrpc.Agent', 'DoRm'): face_utilities.unary_unary_inline(servicer.DoRm),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Agent_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('lbackgrpc.Agent', 'DoBackup'): shared__pb2.BackupCmd.SerializeToString,
      ('lbackgrpc.Agent', 'DoMv'): shared__pb2.MvCmd.SerializeToString,
      ('lbackgrpc.Agent', 'DoRestore'): shared__pb2.RestoreCmd.SerializeToString,
      ('lbackgrpc.Agent', 'DoRm'): shared__pb2.RmCmd.SerializeToString,
    }
    response_deserializers = {
      ('lbackgrpc.Agent', 'DoBackup'): shared__pb2.BackupCmdStatus.FromString,
      ('lbackgrpc.Agent', 'DoMv'): shared__pb2.MvCmdStatus.FromString,
      ('lbackgrpc.Agent', 'DoRestore'): shared__pb2.RestoreCmdStatus.FromString,
      ('lbackgrpc.Agent', 'DoRm'): shared__pb2.RmCmdStatus.FromString,
    }
    cardinalities = {
      'DoBackup': cardinality.Cardinality.STREAM_STREAM,
      'DoMv': cardinality.Cardinality.UNARY_UNARY,
      'DoRestore': cardinality.Cardinality.UNARY_STREAM,
      'DoRm': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'lbackgrpc.Agent', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
